// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bnqiezpltfgixkafizzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucWllenBsdGZnaXhrYWZpenptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzOTI1NTgsImV4cCI6MjA5NDk2ODU1OH0.vwZ4NWSdHo6R3llOKXpUB8-NCkqLaHCqlpvG_fIUaSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);